### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ampf27** [D3Ext/Vulkan#1]
When I run

`ruby main.rb -p Invoke-ReverseShellTcp -o output.ps1 --extreme`

I get the error

```
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- pry (LoadError)
Did you mean?  pty
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from main.rb:14:in `<main>'
```

What may be causing this?

**Comment by D3Ext** [comment]
Have you installed the requirements with the `gem` installer? However try it again, it should work after a little change

**Comment by ampf27** [comment]
I have done

git clone https://github.com/D3Ext/Vulkan
cd Vulkan
gem install colorize httparty optparse
ruby main.rb

And before posting this I tried again 

gem install colorize httparty optparse


but still get the same error

**Comment by D3Ext** [comment]
But have you used this time the new script? Anyway you should install `pry` like this `gem install pry` and it should work

**Comment by ampf27** [comment]
After installing `gem install pry` I was able to make it work however now, when I run `ruby main.rb -p Invoke-ReverseShellTcp -o output.ps1 --extreme `

I get


```
╦  ╦┬ ┬┬  ┬┌─┌─┐┌┐┌
╚╗╔╝│ ││  ├┴┐├─┤│││                                                                                                                                                                                                                         
 ╚╝ └─┘┴─┘┴ ┴┴ ┴┘└┘                                                                                                                                                                                                                         
    by D3Ext v0.1                                                                                                                                                                                                                           
                                                                                                                                                                                                                                            
[+] Iterations: 1
[+] Extreme obfuscation: Yes
[+] Payload: Invoke-ReverseShellTcp
                                                                                                                                                                                                                                            

[!] Invalid payload            
```

Even after reinstalling the script

**Comment by D3Ext** [comment]
Oh sorry I misstyped the payload name, it should be Invoke-PowerShellTcp, fixed on the README.md

**Comment by ampf27** [comment]
Thank you very much

Is now working fine. Just go recommend update the requirements to install gem install pry too.

**Comment by D3Ext** [comment]
Perfect, thank you so much for your help!
